#!/bin/bash

# install-dgl-nh500
#
# Formerly a standalone script for setting up Debian DGL/NetHack 5.0.0
# environment; now a wrapper to provide command-line options for
# dgl-create-chroot and install-dgl-nh500, as well as giving some
# reasonable defaults.
#
# You should run this as root.
#
# Should be run in the directory it was shipped in.
#
# Usage:
# ./install-dgl-nh500 [options]
#
# OPTION [default]                    DESCRIPTION
# --prefix <dir> [/opt/dgamelaunch]   DGL's chroot. All other locations are
#                                     relative to this directory! And
#                                     everything DGL or NetHack need to run
#                                     is in this directory.

# --var <dir> [/var]                  Location for mutable data.

# --etc <dir> [/etc]                  Location for immutable and config data.

# --menudir <dir> [<etc>/menu]         Location for menu files. Really they can
#                                     be anywhere, but this instructs the
#                                     script where to put the default ones.

# --hackdir <dir> [/opt/nh500]        NetHack is built wth this as its prefix.

# --playground <dir> [/var/nh500]     NetHack is built with this as its
#                                     'var playground.'

# --dbfile <sqlite3 db> [<var>/dgamelaunch.db]   The location for the database.

# -q -s --quiet --silent [FLAG]       Causes autogen and make to run quietly.

# --clean                [FLAG]       Skips everything except the clean step.
#                                     Useful if the process gets interrupted...


# Here are some settings which would cause nethack and dgl to be installed
# in a way that reflects the setup instructions provided by Paxed...
# for posterity and testing.
#
# CHROOT="/opt/nethack/nethack.alt.org"
# DGLVAR="/dgldir"
# DGLETC="/."
# MENUDIR="$DGLETC"
# HACKDIR="/nh500"
# PLAYGROUND="/nh500/var"
#
# ./install-dgl-nh500 --prefix /opt/nethack/nethack.alt.org --var /dgldir --etc /. --menudir /. --hackdir /nh500 --playground /nh500/var

while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help|--usage|-?|--?)
      printf "`sed -n '3,55p;55q' $0 | tr -d "#"`\n\n"
      exit 0
      ;;
    -q|-s|--quiet|--silent)
      QUIETMAKE=1
      shift
      ;;
    --prefix)
      CHROOT="/${2#/}"
      CHROOT="${CHROOT%/}"
      shift
      shift
      ;;
    --var)
      DGLVAR="/${2#/}"
      DGLVAR="${DGLVAR%/}"
      shift
      shift
      ;;
    --etc)
      DGLETC="/${2#/}"
      DGLETC="${DGLETC%/}"
      shift
      shift
      ;;
    --menudir)
      MENUDIR="/${2#/}"
      MENUDIR="${MENUDIR%/}"
      shift
      shift
      ;;
    --hackdir)
      HACKDIR="/${2#/}"
      HACKDIR="${HACKDIR%/}"
      shift
      shift
      ;;
    --playground)
      PLAYGROUND="/${2#/}"
      PLAYGROUND="${PLAYGROUND%/}"
      shift
      shift
      ;;
    --dbfile)
      SQLITE_DBFILE="/${2#/}"
      SQLITE_DBFILE="${SQLITE_DBFILE%/}"
      shift
      shift
      ;;
    --nano)
      DGLNANO="/${2#/}"
      DGLNANO="${DGLNANO%/}"
      shift
      shift
      ;;
    # Know what you're doing, or look up a guide on installing NetHack!
    --without-nh500)
      NONH=1
      shift
      ;;
    --fetch-dgl)
      FETCHDGL=1
      ;;
    --)
      set --
      break
      ;;
    -*|--*|*)
      echo "Unknown option $1"
      echo "Try $0 --help"
      exit 1
      ;;
  esac
done

## SETTINGS

# Configuration options for DGL.
# User and group for NetHack and DGL.
USRGRP="games:games"

# DGL chroot. NetHack is actually installed with prefix '/.', and
# then moved later; it ultimately lives entirely within the chroot
# and can't run without it.
#
# If you change this here, you will have to change it in <chroot>/etc/dgamelaunch.conf too.
if [ -z $CHROOT ]; then
  CHROOT="/opt/dgamelaunch"
fi

# In theory these would help keep dgamelaunch organized within its own environment.
#
# Each directory is within the chroot!
#
if [ -z $DGLVAR ]; then
  DGLVAR="/var"
fi
if [ -z $DGLETC ]; then
  DGLETC="/etc"
fi
if [ -z $MENUDIR ]; then
  MENUDIR="$DGLETC/menu"
fi

# The path of the sqlite db for users.
# If this is left undefined (commented out), DGL will be built
# without sqlite3. Also, it'll probably not work.
if [ -z $SQLITE_DBFILE ]; then
  SQLITE_DBFILE="$DGLVAR/dgamelaunch.db"
fi

# These are baked into the patch files, so if you change them here,
# change them there also.
if [ -z $HACKDIR ]; then
  HACKDIR="/opt/nh500"
fi
if [ -z $PLAYGROUND ]; then
  PLAYGROUND="/var/nh500"
fi
if [ -n $NONH ]; then
  # Disable if you already have NetHack-5.0.0 source downloaded and uncompressed.
  FETCHNH=1
  # Disable if you don't want to patch linux.500 and config.h to make life easy.
  PATCHNH=1
  # Disable if you already built NetHack-5.0.0 with your preferred settings!
  BUILDNH=1
  # Disable if you don't want NetHack to be installed in DGL's root.
  INSTALLNH=1
fi

# These are set in the NetHack Makefile, and possibly config.h
# Note: the Makefile only appears after you run:
# sys/unix/setup.sh sys/unix/hints/linux.500
# from inside the NetHack source directory.
COMPRESSBIN="/bin/gzip"
GREPBIN="/bin/grep"

# DON'T CHANGE THESE
WORKDIR="dirname `realpath $0`"
WORKDIR=`$WORKDIR`
NETHACKBIN="$HACKDIR/nethack"



################
# Some functions
errorexit() {
  echo "$@" >&2
  exit 1
}

stripsl() {
  echo "${@#/}"
}

stripsr() {
  echo "${@%/}"
}

standdir() {
  TMP=`stripsl $@`
  TMP=`stripsr $TMP`
  TMP=`echo "$TMP" | tr -d "[:space:]"`
  echo "$TMP"
}

# findlibs from original dgl-create-chroot
findlibs()
{
  for i in "$@"; do
    if [ -z "`ldd "$i" | grep 'not a dynamic executable'`" ]; then
      echo $(ldd "$i" | awk '{ print $3 }' | egrep -v ^'\(')
      echo $(ldd "$i" | grep 'ld-linux' | awk '{print $1}')
    fi
  done
}

# cpbin refactored out of original dgl-create-chroot
cpbin()
{
  if [ -e "`which $1`" ]; then
    NEWDIR=`dirname $1`
    NEWDIR=`standdir $NEWDIR`
    echo "Copying $1 to `pwd`/$NEWDIR"
    mkdir -p "$NEWDIR"
    cp "`which $1`" "$NEWDIR/"
    LIBS="$LIBS `findlibs $1`"
  fi
}

CHROOT=`standdir $CHROOT`
DGLVAR=`standdir $DGLVAR`
DGLETC=`standdir $DGLETC`
MENUDIR=`standdir $MENUDIR`
SQLITE_DBFILE=`standdir $SQLITE_DBFILE`
HACKDIR=`standdir $HACKDIR`
PLAYGROUND=`standdir $PLAYGROUND`
COMPRESSBIN=`standdir $COMPRESSBIN`
GREPBIN=`standdir $GREPBIN`
NETHACKBIN=`standdir $NETHACKBIN`
WORKDIR=`standdir $WORKDIR`
